name: kurs_oop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  auto_route: ^7.8.4 
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  talker_flutter: ^3.5.4
  talker_bloc_logger: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_local_notifications: ^17.0.1
  flutter_launcher_icons: ^0.13.1
  timezone: ^0.9.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  build_runner:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/tasker_icon.png"
  

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratAlternates/MontserratAlternates-Light.ttf
        - asset: assets/fonts/MontserratAlternates/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/MontserratAlternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates/MontserratAlternates-SemiBold.ttf
        - asset: assets/fonts/MontserratAlternates/MontserratAlternates-Bold.ttf